### ISSUE TITLE
Usage example for packet type for accounting request RFC2866?

### ISSUE THREAD

**Issue by monelgordillo** [jyggen/radius#1]
Is there a usage example for packet type for accounting request RFC2866?

**Comment by jyggen** [comment]
I'll admit that I haven't actively used Radius nor this library for over a year, so my memory might be a bit rusty - but I believe something like this should work:
```
$response = $client->send(new Packet(PacketType::ACCOUNTING_REQUEST(), /* secret */ 'xyzzy5461', [
    'Acct-Status-Type' => Rfc2866::ACCT_STATUS_TYPE_INTERIM_UPDATE,
    'Acct-Session-Id' => '123',
    'Acct-Session-Time' => 3600,
]));
```

Which attributes you need to send in the accounting request depends on what you want to achieve, but the code above should get you started at least. Good luck and let me know if you run into any bugs with the library!

**Comment by monelgordillo** [comment]
I tried it. 

I'm getting this from the PHP page: 

Fatal error: Uncaught Boo\Radius\Exceptions\ClientException: Client timed out while waiting for a response in /var/www/html/authweb/vendor/boo/radius/src/Client.php:72 Stack trace: #0 /var/www/html/authweb/fas-aes2.php(263): Boo\Radius\Client->send(Object(Boo\Radius\Packet)) #1 {main} thrown in /var/www/html/authweb/vendor/boo/radius/src/Client.php on line 72

From the radius side, I see this:

31) sql: EXPAND UPDATE radacct SET acctupdatetime  = (@acctupdatetime_old:=acctupdatetime), acctupdatetime  = FROM_UNIXTIME(%{integer:Event-Timestamp}), acctinterval    = %{integer:Event-Timestamp} - UNIX_TIMESTAMP(@acctupdatetime_old), framedipaddress = '%{Framed-IP-Address}', acctsessiontime = %{%{Acct-Session-Time}:-NULL}, acctinputoctets = '%{%{Acct-Input-Gigawords}:-0}' << 32 | '%{%{Acct-Input-Octets}:-0}', acctoutputoctets = '%{%{Acct-Output-Gigawords}:-0}' << 32 | '%{%{Acct-Output-Octets}:-0}' WHERE AcctUniqueId = '%{Acct-Unique-Session-Id}'
(31) sql:    --> UPDATE radacct SET acctupdatetime  = (@acctupdatetime_old:=acctupdatetime), acctupdatetime  = FROM_UNIXTIME(1588291505), acctinterval    = 1588291505 - UNIX_TIMESTAMP(@acctupdatetime_old), framedipaddress = '', acctsessiontime = 3600, acctinputoctets = '0' << 32 | '0', acctoutputoctets = '0' << 32 | '0' WHERE AcctUniqueId = '3ee917e403669b0627d8f549137c4dac'
(31) sql: Executing query: UPDATE radacct SET acctupdatetime  = (@acctupdatetime_old:=acctupdatetime), acctupdatetime  = FROM_UNIXTIME(1588291505), acctinterval    = 1588291505 - UNIX_TIMESTAMP(@acctupdatetime_old), framedipaddress = '', acctsessiontime = 3600, acctinputoctets = '0' << 32 | '0', acctoutputoctets = '0' << 32 | '0' WHERE AcctUniqueId = '3ee917e403669b0627d8f549137c4dac'
**(31) sql: ERROR: rlm_sql_mysql: ERROR 1054 (Unknown column 'acctupdatetime' in 'field list'): 42S22**
(31) sql: SQL query returned: server error

**Comment by monelgordillo** [comment]
I figured it out.  There seems to be an issue with FreeRADIUS 3.0.13.
I had to add these 2 columns manually to the radius database:
acctupdatetime
acctinterval

Its weird.  Thank you for your help.
