### ISSUE TITLE
Any update for latest composer?

### ISSUE THREAD

**Issue by rjjrbatarao** [jyggen/radius#2]
I can say this is the best implementation for radius in php so far do you mind if you can update this to latest composer? im getting problem installing via composer so I just copied and manually add as classmap in composer

**Comment by jyggen** [comment]
Hello! 👋 

Happy to hear this old package is still useful to someone! Could you perhaps elaborate what you mean by updating it to the latest Composer? What errors are you facing?

**Comment by rjjrbatarao** [comment]
@jyggen I was trying to install this using composer require boo/radius and it gives errors like this
```
Could not find package boo/radius in any version matching your PHP version, PHP extensions and Composer version:
    - boo/radius 1.x-dev requires ext-sockets * but it is not present.

  Additionally, the package was only found with a stability of "dev" while your minimum stability is "stable".
```
here is my environment
```
Composer version 2.6.5
PHP 8.2.7
```
Below is a working radius SERVER!! using boo/radius library with the use of [workerman](https://github.com/walkor/workerman), here is my simple worker start.php which surprisingly works well with my Mikrotik router as radius server :) , my sources are messy since im using your library as folder and manually adding as classmap in composer, maybe you can change your underlying udp implementation using the workerman which can be a tcp/udp [client](https://github.com/walkor/workerman/issues/892) or server, possibility could be endless :) Im now currently working on the md5 mschapv1 and v2 implementation as verification for authentication, I just extracted the md5 libraries from dapp\radius which uses the pear Crypt library so its quite easy to poke around.
```php
<?php

use Workerman\Worker;
use Boo\Radius\Packet;
use Boo\Radius\PacketType;
use Boo\Radius\PacketEncoder;

require_once __DIR__ . '/vendor/autoload.php';

// #### create socket and listen radius 1812 port ####
$udp_worker = new Worker('udp://0.0.0.0:1812');

// 4 processes
$udp_worker->count = 4;

// Emitted when new connection come
$udp_worker->onConnect = function ($connection) {
	var_dump("New Connection\n");
};

// Emitted when data received
$udp_worker->onMessage = function ($connection, $data) {
	$encoder = new PacketEncoder();
	$packet = $encoder->decode($data, 'secret');
	var_dump(json_encode($packet->getAttributes(), JSON_INVALID_UTF8_IGNORE));
// Do some logic on the response PacketType to accept or reject based on the decoded username and password on this case it just accepts everything
	$response = $encoder->encode(new Packet(
		PacketType::ACCESS_ACCEPT(),
		'secret',
		[
			'Session-Timeout' => 60 * 5,
			'Acct-Interim-Interval' => 60,
		],
		$packet->getAuthenticator(),
		$packet->getIdentifier()
	));

	$connection->send($response);
};

// Emitted when connection is closed
$udp_worker->onClose = function ($connection) {
	var_dump("Connection closed\n");
};

Worker::runAll();

```
![image](https://github.com/jyggen/radius/assets/50077340/d8eda38c-8f39-4b16-aee7-a44006880d27)
![image](https://github.com/jyggen/radius/assets/50077340/8768739f-37b9-41bf-964f-09c9a994972d)

I've also implemented radius accounting server, im working on the coa, and the daily weekly and monthly timers now, your library is just perfect when combined with workerman since workerman also has built in Timers :) this can be a powerfull freeradius alternative

**Comment by jyggen** [comment]
The error message is pretty clear. This package requires `ext-sockets` due to the dependency on `clue/socket-raw` (which is used in `Boo\Radius\Client`) and it is not installed in the environment where you're trying to install the package. Install the `sockets` extension and you should have more success.
